#define SECRET_MQTT_USERNAME "MwoJFAQBEiAIHCMxBy8jDi0"
#define SECRET_MQTT_CLIENT_ID "MwoJFAQBEiAIHCMxBy8jDi0"
#define SECRET_MQTT_PASSWORD "s5WKre6+yCHXkch+NzmNGDaZ"

#define CHANNEL_ID 2028262
#define MQTT_PORT 1883
#define UPDATE_TIME_INTERVAL 4000
#define TRAIN_FIELDS 2
#define TRAIN_POS_FIELD 1
#define STATION_POS_FIELD 3
#define TRAIN_SPEED_FIELD 4
#define TRAIN_SPEED_CONTROL_FIELD 5
