#define SECRET_MQTT_USERNAME "DQQRGRolEhElAxstJCAuFxA"
#define SECRET_MQTT_CLIENT_ID "DQQRGRolEhElAxstJCAuFxA"
#define SECRET_MQTT_PASSWORD "xO5tnrFZitHmPm+yiu++IIuK"

#define MQTT_PORT 1883
#define TRAIN_SPEED_CONTROL_FIELD 4
